CREATE DATABASE IF NOT EXISTS `auth_db`;
CREATE DATABASE IF NOT EXISTS `usuarios_db`;
CREATE DATABASE IF NOT EXISTS `pacientes_db`;
CREATE DATABASE IF NOT EXISTS `medicos_db`;
CREATE DATABASE IF NOT EXISTS `citas_db`;
CREATE DATABASE IF NOT EXISTS `historiales_db`;
